name: VPS SSH

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH + Start Server
        run: |
          sudo apt update && sudo apt install -y openssh-server
          echo "root:root" | sudo chpasswd
          sudo service ssh start

      - name: Create SSH Tunnel with Pinggy
        run: |
          ssh -p 443 \
              -R0:localhost:22 \
              -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=30 \
              tcp@eu.pinggy.io > tunnel.log 2>&1 &

          echo "⏳ في انتظار الرابط من Pinggy..."
          for i in {1..30}; do
            LINK=$(grep -o 'tcp://[0-9a-zA-Z.-]*:[0-9]*' tunnel.log | grep '.tcp.pinggy.io')
            if [ ! -z "$LINK" ]; then
              echo "===================="
              echo "🌍 SSH Connection Info:"
              echo "$LINK" | sed 's#tcp://#ssh root@#'
              echo "Password: root"
              echo "===================="
              break
            fi
            sleep 2
          done

          sleep 21600
