name: Ubuntu SSH via Pinggy

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: ุชุซุจูุช OpenSSH Server ูุชูุนูู Root
        run: |
          sudo apt update && sudo apt install -y openssh-server
          echo "root:root" | sudo chpasswd
          sudo sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service ssh restart

      - name: ุชุดุบูู Pinggy ุนุจุฑ SSH ูุทุจุงุนุฉ ุฑุงุจุท ุงูุงุชุตุงู
        shell: bash
        run: |
          echo "๐ ูุนูููุงุช ุงูุงุชุตุงู ุจู VPS:"
          echo "๐ค ุงููุณุชุฎุฏู: root"
          echo "๐ ูููุฉ ุงููุฑูุฑ: root"
          echo "โณ ุฌุงุฑู ุฅูุดุงุก ููู Pinggy..."

          ssh -p 443 -R0:localhost:22 -o StrictHostKeyChecking=no 6PJwxLEUlPO+tcp@eu.free.pinggy.io | tee pinggy_log.txt &

          sleep 10
          echo "๐ ุฑุงุจุท ุงูุงุชุตุงู:"
          grep -i "tcp://" pinggy_log.txt || echo "โ ูู ูุชู ุงูุนุซูุฑ ุนูู ุฑุงุจุท."
          echo "๐ ุณูุชู ุงูุฅุจูุงุก ุนูู ุงูุงุชุตุงู ููุฏุฉ 6 ุณุงุนุงุช..."
          sleep 21600
