name: VPS SSH via Pinggy

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: ุชุซุจูุช OpenSSH ูุชุดุบููู
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          echo "root:root" | sudo chpasswd
          sudo service ssh start
          sudo ufw allow ssh || true

      - name: ุชุดุบูู Pinggy ูุนูู ููู SSH
        shell: bash
        run: |
          echo "๐ ูุนูููุงุช ุงูุงุชุตุงู ุจุงูู VPS:"
          echo "๐ค ุงููุณุชุฎุฏู: root"
          echo "๐ ูููุฉ ุงููุฑูุฑ: root"
          echo "โณ ุฌุงุฑู ุฅูุดุงุก ููู Pinggy..."

          # ูุดุบู ุงุชุตุงู Pinggy ููุฎุฒู ุงูููุฌ
          ssh -p 443 \
              -R0:localhost:22 \
              -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=30 \
              tcp@eu.pinggy.io > pinggy_log.txt 2>&1 &

          # ููุชุธุฑ ูุญุฏ ูุง ูุทูุน ุงููููู
          for i in {1..30}; do
            LINK=$(grep -o 'tcp://[0-9a-zA-Z.-]*:[0-9]*' pinggy_log.txt | grep '.tcp.pinggy.io')
            if [ ! -z "$LINK" ]; then
              echo "===================="
              echo "๐ ุฃูุฑ ุงูุงุชุตุงู ุจุงูู VPS:"
              # ูุทุจุน ุฑุงุจุท SSH ุฌุงูุฒ
              echo "$LINK" | sed 's#tcp://#ssh root@#'
              echo "๐ ูููุฉ ุงููุฑูุฑ: root"
              echo "===================="
              break
            fi
            sleep 2
          done

          echo "๐ ุณูุชู ุงูุฅุจูุงุก ุนูู ุงูุงุชุตุงู ููุฏุฉ 6 ุณุงุนุงุช..."
          sleep 21600
