name: VPS SSH

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH + Start Server
        run: |
          sudo apt update && sudo apt install -y openssh-server
          echo "root:root" | sudo chpasswd
          sudo service ssh start

      - name: Create SSH Tunnel with Pinggy
        run: |
          # ุงูุชุญ ุจูุฑุช 22 ุนุจุฑ Pinggy
          ssh -p 443 \
              -R0:localhost:22 \
              -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=30 \
              tcp@eu.pinggy.io > tunnel.log 2>&1 &

          sleep 20
          echo "===================="
          echo "๐ SSH Connection Info:"
          grep -o 'tcp://[0-9a-zA-Z.-]*:[0-9]*' tunnel.log | sed 's/tcp/ssh root@/'
          echo "Password: root"
          echo "===================="

          # ูุฎููู ุดุบุงู 6 ุณุงุนุงุช
          sleep 21600
